version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - echo No tests to run
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.py
    - config.py
    - wsgi.py
    - requirements.txt
    - appspec.yml
    - scripts/**/*
    - static/**/*
    - templates/**/*
  discard-paths: no